// Auto-generated by json_to_cypher.py - do not edit by hand.
// Re-run the script after changing the .structure.json.

// --- Constraints (unique ids, idempotent load) ---
CREATE CONSTRAINT lecture_id IF NOT EXISTS FOR (n:Lecture) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT chapter_id IF NOT EXISTS FOR (n:Chapter) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT topic_id IF NOT EXISTS FOR (n:Topic) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT subtopic_id IF NOT EXISTS FOR (n:Subtopic) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT concept_id IF NOT EXISTS FOR (n:Concept) REQUIRE n.id IS UNIQUE;

// --- Nodes ---
MERGE (n:Lecture {id:'BDT'})
  SET n.name='Big-Data-Technologien', n.code='BDT', n.degreeType='Master', n.term='2. Fachsemester', n.PO='2019', n.ECTS=6, n.prof='Prof. Dr. Max Mustermann';
MERGE (n:Chapter {id:'BDT_CH01'})
  SET n.name='Architekturen & Relationale Anfrageverarbeitung', n.index=1;
MERGE (n:Topic {id:'BDT_CH01_T01'})
  SET n.name='Begriffe im Umfeld von Datenbanksystemen und Big Data', n.index=1;
MERGE (n:Concept {id:'BDT_CH01_T01_C01'})
  SET n.name='Informationssystem';
MERGE (n:Concept {id:'BDT_CH01_T01_C02'})
  SET n.name='Anwendungsprogramm';
MERGE (n:Concept {id:'BDT_CH01_T01_C03'})
  SET n.name='Datenbank-System (DBS)';
MERGE (n:Concept {id:'BDT_CH01_T01_C04'})
  SET n.name='Datenbank-Management-System (DBMS)';
MERGE (n:Concept {id:'BDT_CH01_T01_C05'})
  SET n.name='Datenbank (DB)';
MERGE (n:Concept {id:'BDT_CH01_T01_C06'})
  SET n.name='Unterschied DBMS & Daten-Management-Systeme';
MERGE (n:Concept {id:'BDT_CH01_T01_C07'})
  SET n.name='Datenunabhängigkeit';
MERGE (n:Subtopic {id:'BDT_CH01_T01_S01'})
  SET n.name='Motivation für den Einsatz';
MERGE (n:Concept {id:'BDT_CH01_T01_S01_C01'})
  SET n.name='Datenverwaltung';
MERGE (n:Concept {id:'BDT_CH01_T01_S01_C02'})
  SET n.name='Skalierbarkeit & Effizienz';
MERGE (n:Concept {id:'BDT_CH01_T01_S01_C03'})
  SET n.name='Strukturierte Datenmodelle';
MERGE (n:Concept {id:'BDT_CH01_T01_S01_C04'})
  SET n.name='Transaktionsmanagement';
MERGE (n:Concept {id:'BDT_CH01_T01_S01_C05'})
  SET n.name='Datenschutz und Datensicherheit';
MERGE (n:Subtopic {id:'BDT_CH01_T01_S02'})
  SET n.name='Datenmodellierung';
MERGE (n:Concept {id:'BDT_CH01_T01_S02_C01'})
  SET n.name='Konzeptuelle Ebene';
MERGE (n:Subtopic {id:'BDT_CH01_T01_S02_S01'})
  SET n.name='Logische Ebene';
MERGE (n:Concept {id:'BDT_CH01_T01_S02_S01_C01'})
  SET n.name='Relationales Datenmodell';
MERGE (n:Concept {id:'BDT_CH01_T01_S02_S01_C02'})
  SET n.name='Aggregat-orientiertes Datenmodell (XML/JSON)';
MERGE (n:Concept {id:'BDT_CH01_T01_S02_C02'})
  SET n.name='Physische Ebene';
MERGE (n:Topic {id:'BDT_CH01_T02'})
  SET n.name='Architekturen für Datenbank-Management-Systeme', n.index=2;
MERGE (n:Concept {id:'BDT_CH01_T02_C01'})
  SET n.name='Client-Server-Architekturen';
MERGE (n:Subtopic {id:'BDT_CH01_T02_S01'})
  SET n.name='Skalierbarkeit';
MERGE (n:Concept {id:'BDT_CH01_T02_S01_C01'})
  SET n.name='Vertikale Skalierung';
MERGE (n:Concept {id:'BDT_CH01_T02_S01_C02'})
  SET n.name='Horizontale Skalierung';
MERGE (n:Concept {id:'BDT_CH01_T02_C02'})
  SET n.name='Probleme verteilter DB-Systeme';
MERGE (n:Topic {id:'BDT_CH01_T03'})
  SET n.name='Big-Data-Architekturen', n.index=3;
MERGE (n:Subtopic {id:'BDT_CH01_T03_S01'})
  SET n.name='Big Data';
MERGE (n:Concept {id:'BDT_CH01_T03_S01_C01'})
  SET n.name='Volume';
MERGE (n:Concept {id:'BDT_CH01_T03_S01_C02'})
  SET n.name='Velocity';
MERGE (n:Concept {id:'BDT_CH01_T03_S01_C03'})
  SET n.name='Variety';
MERGE (n:Subtopic {id:'BDT_CH01_T03_S02'})
  SET n.name='Lambda-Architektur';
MERGE (n:Concept {id:'BDT_CH01_T03_S02_C01'})
  SET n.name='Batch-Layer';
MERGE (n:Concept {id:'BDT_CH01_T03_S02_C02'})
  SET n.name='Speed-Layer';
MERGE (n:Concept {id:'BDT_CH01_T03_S02_C03'})
  SET n.name='Serving-Layer';
MERGE (n:Subtopic {id:'BDT_CH01_T03_S03'})
  SET n.name='Kappa-Architektur';
MERGE (n:Topic {id:'BDT_CH01_T04'})
  SET n.name='Anfrageverarbeitung und Speicherstrukturen in einem DBMS', n.index=4;
MERGE (n:Concept {id:'BDT_CH01_T04_C01'})
  SET n.name='Anfrageverarbeitung in relationalen DBMS';
MERGE (n:Concept {id:'BDT_CH01_T04_C02'})
  SET n.name='Blockweiser Festplattenzugriff';
MERGE (n:Concept {id:'BDT_CH01_T04_C03'})
  SET n.name='Kostenfunktion';
MERGE (n:Subtopic {id:'BDT_CH01_T04_S01'})
  SET n.name='Indexstrukturen';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C01'})
  SET n.name='Primärindex';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C02'})
  SET n.name='Sekundärindex';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C03'})
  SET n.name='Clustered';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C04'})
  SET n.name='Unclustered';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C05'})
  SET n.name='Bäume (Mehrstufige Hierarchien)';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C06'})
  SET n.name='Mehrweg-Suchbäume';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C07'})
  SET n.name='B-Baum';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C08'})
  SET n.name='B+-Baum';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C09'})
  SET n.name='Heap-Datei (Haufen)';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C10'})
  SET n.name='Sortierte Datei';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C11'})
  SET n.name='Clustered Index';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C12'})
  SET n.name='Unclustered Tree Index';
MERGE (n:Concept {id:'BDT_CH01_T04_S01_C13'})
  SET n.name='Unclustered Hash Index';
MERGE (n:Topic {id:'BDT_CH01_T05'})
  SET n.name='Implementierung von Relationalen Operationen', n.index=5;
MERGE (n:Subtopic {id:'BDT_CH01_T05_S01'})
  SET n.name='Sortieren';
MERGE (n:Concept {id:'BDT_CH01_T05_S01_C01'})
  SET n.name='Zwei-Wege-Merge-Sort';
MERGE (n:Concept {id:'BDT_CH01_T05_S01_C02'})
  SET n.name='Generelles Merge-Sort';
MERGE (n:Subtopic {id:'BDT_CH01_T05_S02'})
  SET n.name='Join';
MERGE (n:Concept {id:'BDT_CH01_T05_S02_C01'})
  SET n.name='Naive Implementierung';
MERGE (n:Concept {id:'BDT_CH01_T05_S02_C02'})
  SET n.name='Block Nested Loop Join';
MERGE (n:Concept {id:'BDT_CH01_T05_S02_C03'})
  SET n.name='Sort-Merge Join';
MERGE (n:Concept {id:'BDT_CH01_T05_S02_C04'})
  SET n.name='Hash Join';
MERGE (n:Topic {id:'BDT_CH01_T06'})
  SET n.name='Anfrageoptimierung', n.index=6;
MERGE (n:Concept {id:'BDT_CH01_T06_C01'})
  SET n.name='Optimierung auf logischer Ebene';
MERGE (n:Concept {id:'BDT_CH01_T06_C02'})
  SET n.name='Optimierung auf physischer Ebene';
MERGE (n:Concept {id:'BDT_CH01_T06_C03'})
  SET n.name='Inkrementelles Vorgehen';
MERGE (n:Concept {id:'BDT_CH01_T06_C04'})
  SET n.name='Aggregationen';
MERGE (n:Concept {id:'BDT_CH01_T06_C05'})
  SET n.name='Einfügen von zusätzlichen Gruppierungen';
MERGE (n:Subtopic {id:'BDT_CH01_T06_S01'})
  SET n.name='Vorgehen bei Optimierung';
MERGE (n:Concept {id:'BDT_CH01_T06_S01_C01'})
  SET n.name='Reduktion des Suchraums (Heuristiken)';
MERGE (n:Subtopic {id:'BDT_CH01_T06_S01_S01'})
  SET n.name='Dynamische Programmierung';
MERGE (n:Concept {id:'BDT_CH01_T06_S01_S01_C01'})
  SET n.name='Optimalitätsprinzip der Dynamischen Programmierung';
MERGE (n:Topic {id:'BDT_CH01_T07'})
  SET n.name='Weitere Methoden zur Optimierung von Anfragen', n.index=7;
MERGE (n:Concept {id:'BDT_CH01_T07_C01'})
  SET n.name='Index-Only Queries';
MERGE (n:Concept {id:'BDT_CH01_T07_C02'})
  SET n.name='Materialized Views';
MERGE (n:Subtopic {id:'BDT_CH01_T07_S01'})
  SET n.name='Physische Optimierung in PostgreSQL';
MERGE (n:Concept {id:'BDT_CH01_T07_S01_C01'})
  SET n.name='shared_buffers';
MERGE (n:Concept {id:'BDT_CH01_T07_S01_C02'})
  SET n.name='effective_cache_size';
MERGE (n:Concept {id:'BDT_CH01_T07_S01_C03'})
  SET n.name='work_mem';
MERGE (n:Concept {id:'BDT_CH01_T07_S01_C04'})
  SET n.name='maintenance_work_mem';

// --- Relationships ---
MATCH (p:Lecture {id:'BDT'}), (c:Chapter {id:'BDT_CH01'}) MERGE (p)-[:HAS_CHAPTER]->(c);
MATCH (p:Chapter {id:'BDT_CH01'}), (c:Topic {id:'BDT_CH01_T01'}) MERGE (p)-[:HAS_TOPIC]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Concept {id:'BDT_CH01_T01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Concept {id:'BDT_CH01_T01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Concept {id:'BDT_CH01_T01_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Concept {id:'BDT_CH01_T01_C04'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Concept {id:'BDT_CH01_T01_C05'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Concept {id:'BDT_CH01_T01_C06'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Concept {id:'BDT_CH01_T01_C07'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Subtopic {id:'BDT_CH01_T01_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S01'}), (c:Concept {id:'BDT_CH01_T01_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S01'}), (c:Concept {id:'BDT_CH01_T01_S01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S01'}), (c:Concept {id:'BDT_CH01_T01_S01_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S01'}), (c:Concept {id:'BDT_CH01_T01_S01_C04'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S01'}), (c:Concept {id:'BDT_CH01_T01_S01_C05'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T01'}), (c:Subtopic {id:'BDT_CH01_T01_S02'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S02'}), (c:Concept {id:'BDT_CH01_T01_S02_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S02'}), (c:Subtopic {id:'BDT_CH01_T01_S02_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S02_S01'}), (c:Concept {id:'BDT_CH01_T01_S02_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S02_S01'}), (c:Concept {id:'BDT_CH01_T01_S02_S01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T01_S02'}), (c:Concept {id:'BDT_CH01_T01_S02_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Chapter {id:'BDT_CH01'}), (c:Topic {id:'BDT_CH01_T02'}) MERGE (p)-[:HAS_TOPIC]->(c);
MATCH (p:Topic {id:'BDT_CH01_T02'}), (c:Concept {id:'BDT_CH01_T02_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T02'}), (c:Subtopic {id:'BDT_CH01_T02_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T02_S01'}), (c:Concept {id:'BDT_CH01_T02_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T02_S01'}), (c:Concept {id:'BDT_CH01_T02_S01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T02'}), (c:Concept {id:'BDT_CH01_T02_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Chapter {id:'BDT_CH01'}), (c:Topic {id:'BDT_CH01_T03'}) MERGE (p)-[:HAS_TOPIC]->(c);
MATCH (p:Topic {id:'BDT_CH01_T03'}), (c:Subtopic {id:'BDT_CH01_T03_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T03_S01'}), (c:Concept {id:'BDT_CH01_T03_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T03_S01'}), (c:Concept {id:'BDT_CH01_T03_S01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T03_S01'}), (c:Concept {id:'BDT_CH01_T03_S01_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T03'}), (c:Subtopic {id:'BDT_CH01_T03_S02'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T03_S02'}), (c:Concept {id:'BDT_CH01_T03_S02_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T03_S02'}), (c:Concept {id:'BDT_CH01_T03_S02_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T03_S02'}), (c:Concept {id:'BDT_CH01_T03_S02_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T03'}), (c:Subtopic {id:'BDT_CH01_T03_S03'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Chapter {id:'BDT_CH01'}), (c:Topic {id:'BDT_CH01_T04'}) MERGE (p)-[:HAS_TOPIC]->(c);
MATCH (p:Topic {id:'BDT_CH01_T04'}), (c:Concept {id:'BDT_CH01_T04_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T04'}), (c:Concept {id:'BDT_CH01_T04_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T04'}), (c:Concept {id:'BDT_CH01_T04_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T04'}), (c:Subtopic {id:'BDT_CH01_T04_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C04'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C05'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C06'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C07'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C08'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C09'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C10'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C11'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C12'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T04_S01'}), (c:Concept {id:'BDT_CH01_T04_S01_C13'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Chapter {id:'BDT_CH01'}), (c:Topic {id:'BDT_CH01_T05'}) MERGE (p)-[:HAS_TOPIC]->(c);
MATCH (p:Topic {id:'BDT_CH01_T05'}), (c:Subtopic {id:'BDT_CH01_T05_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T05_S01'}), (c:Concept {id:'BDT_CH01_T05_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T05_S01'}), (c:Concept {id:'BDT_CH01_T05_S01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T05'}), (c:Subtopic {id:'BDT_CH01_T05_S02'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T05_S02'}), (c:Concept {id:'BDT_CH01_T05_S02_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T05_S02'}), (c:Concept {id:'BDT_CH01_T05_S02_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T05_S02'}), (c:Concept {id:'BDT_CH01_T05_S02_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T05_S02'}), (c:Concept {id:'BDT_CH01_T05_S02_C04'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Chapter {id:'BDT_CH01'}), (c:Topic {id:'BDT_CH01_T06'}) MERGE (p)-[:HAS_TOPIC]->(c);
MATCH (p:Topic {id:'BDT_CH01_T06'}), (c:Concept {id:'BDT_CH01_T06_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T06'}), (c:Concept {id:'BDT_CH01_T06_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T06'}), (c:Concept {id:'BDT_CH01_T06_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T06'}), (c:Concept {id:'BDT_CH01_T06_C04'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T06'}), (c:Concept {id:'BDT_CH01_T06_C05'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T06'}), (c:Subtopic {id:'BDT_CH01_T06_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T06_S01'}), (c:Concept {id:'BDT_CH01_T06_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T06_S01'}), (c:Subtopic {id:'BDT_CH01_T06_S01_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T06_S01_S01'}), (c:Concept {id:'BDT_CH01_T06_S01_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Chapter {id:'BDT_CH01'}), (c:Topic {id:'BDT_CH01_T07'}) MERGE (p)-[:HAS_TOPIC]->(c);
MATCH (p:Topic {id:'BDT_CH01_T07'}), (c:Concept {id:'BDT_CH01_T07_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T07'}), (c:Concept {id:'BDT_CH01_T07_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Topic {id:'BDT_CH01_T07'}), (c:Subtopic {id:'BDT_CH01_T07_S01'}) MERGE (p)-[:HAS_SUBTOPIC]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T07_S01'}), (c:Concept {id:'BDT_CH01_T07_S01_C01'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T07_S01'}), (c:Concept {id:'BDT_CH01_T07_S01_C02'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T07_S01'}), (c:Concept {id:'BDT_CH01_T07_S01_C03'}) MERGE (p)-[:HAS_CONCEPT]->(c);
MATCH (p:Subtopic {id:'BDT_CH01_T07_S01'}), (c:Concept {id:'BDT_CH01_T07_S01_C04'}) MERGE (p)-[:HAS_CONCEPT]->(c);

// --- Summary ---
// Nodes: 83 total | Chapter=1, Concept=61, Lecture=1, Subtopic=13, Topic=7
// Relationships: 82
//
// Useful checks:
//   MATCH (l:Lecture {id:'BDT'})-[:HAS_CHAPTER]->(:Chapter)-[:HAS_TOPIC]->(t) RETURN t.index, t.name ORDER BY t.index;
//   MATCH p=(t:Topic)-[:HAS_SUBTOPIC|HAS_CONCEPT*]->(n) RETURN p;
