#!/usr/bin/env python3
"""
json_to_cypher.py - Turn a lecture-structure JSON into Neo4j Cypher.

Usage:
    python3 json_to_cypher.py structure.json [output.cypher]

The JSON describes one Lecture > Chapter > Topic > Subtopic(recursive) > Concept
hierarchy. IDs are generated automatically from the hierarchy (see scheme below),
so the JSON only needs names/structure. An explicit "id" on any node overrides
the generated one.

ID scheme (globally unique, supports many lectures in one DB):
    Lecture   <CODE>                         e.g. BDT
    Chapter   <CODE>_CH<nn>                   e.g. BDT_CH01
    Topic     <CHAPTER>_T<nn>                 e.g. BDT_CH01_T03
    Subtopic  <PARENT>_S<nn>                  e.g. BDT_CH01_T01_S02
    Concept   <PARENT>_C<nn>                  e.g. BDT_CH01_T01_S02_C01
(<nn> = zero-padded order within the parent, per node type.)

Relationships:
    (Lecture)-[:HAS_CHAPTER]->(Chapter)
    (Chapter)-[:HAS_TOPIC]->(Topic)
    (Topic|Subtopic)-[:HAS_SUBTOPIC]->(Subtopic)
    (Topic|Subtopic)-[:HAS_CONCEPT]->(Concept)
"""
import json
import sys

NODE_LABEL = {"subtopic": "Subtopic", "concept": "Concept"}
NODE_REL = {"subtopic": "HAS_SUBTOPIC", "concept": "HAS_CONCEPT"}


def esc(value):
    """Escape a value for a single-quoted Cypher string."""
    return str(value).replace("\\", "\\\\").replace("'", "\\'")


def fmt(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + esc(value) + "'"


class Builder:
    def __init__(self):
        self.nodes = []   # (label, id, props_dict)  - in tree (DFS) order
        self.rels = []    # (parent_label, parent_id, rel, child_label, child_id)
        self.seen = set()

    def add_node(self, label, nid, props):
        if nid in self.seen:
            raise SystemExit("ERROR: duplicate id '%s'" % nid)
        self.seen.add(nid)
        self.nodes.append((label, nid, props))

    def walk_children(self, children, parent_label, parent_id):
        counters = {"subtopic": 0, "concept": 0}
        for child in children:
            ctype = child["type"]
            if ctype not in NODE_LABEL:
                raise SystemExit("ERROR: unknown node type '%s'" % ctype)
            counters[ctype] += 1
            suffix = "S" if ctype == "subtopic" else "C"
            nid = child.get("id") or "%s_%s%02d" % (parent_id, suffix, counters[ctype])
            label = NODE_LABEL[ctype]
            self.add_node(label, nid, {"name": child["name"]})
            self.rels.append((parent_label, parent_id, NODE_REL[ctype], label, nid))
            self.walk_children(child.get("children", []), label, nid)

    def build(self, data):
        lec = data["lecture"]
        code = lec["code"]
        lec_id = lec.get("id") or code
        self.add_node("Lecture", lec_id, {
            "name": lec["name"], "code": code,
            "degreeType": lec.get("degreeType", ""),
            "term": lec.get("term", ""),
            "PO": lec.get("PO", ""),
            "prof": lec.get("prof", ""),
        })

        ch = data["chapter"]
        ch_idx = ch["index"]
        ch_id = ch.get("id") or "%s_CH%02d" % (code, ch_idx)
        self.add_node("Chapter", ch_id, {"name": ch["name"], "index": ch_idx})
        self.rels.append(("Lecture", lec_id, "HAS_CHAPTER", "Chapter", ch_id))

        for i, topic in enumerate(data["topics"], start=1):
            t_idx = topic.get("index", i)
            t_id = topic.get("id") or "%s_T%02d" % (ch_id, t_idx)
            self.add_node("Topic", t_id, {"name": topic["name"], "index": t_idx})
            self.rels.append(("Chapter", ch_id, "HAS_TOPIC", "Topic", t_id))
            self.walk_children(topic.get("children", []), "Topic", t_id)

    def to_cypher(self):
        out = []
        out.append("// Auto-generated by json_to_cypher.py - do not edit by hand.")
        out.append("// Re-run the script after changing the .structure.json.\n")

        out.append("// --- Constraints (unique ids, idempotent load) ---")
        for label in ["Lecture", "Chapter", "Topic", "Subtopic", "Concept"]:
            out.append(
                "CREATE CONSTRAINT %s_id IF NOT EXISTS "
                "FOR (n:%s) REQUIRE n.id IS UNIQUE;" % (label.lower(), label)
            )
        out.append("")

        out.append("// --- Nodes ---")
        for label, nid, props in self.nodes:
            assigns = ", ".join("n.%s=%s" % (k, fmt(v)) for k, v in props.items())
            out.append("MERGE (n:%s {id:'%s'})\n  SET %s;" % (label, nid, assigns))
        out.append("")

        out.append("// --- Relationships ---")
        for pl, pid, rel, cl, cid in self.rels:
            out.append(
                "MATCH (p:%s {id:'%s'}), (c:%s {id:'%s'}) "
                "MERGE (p)-[:%s]->(c);" % (pl, pid, cl, cid, rel)
            )
        out.append("")

        counts = {}
        for label, _, _ in self.nodes:
            counts[label] = counts.get(label, 0) + 1
        out.append("// --- Summary ---")
        out.append("// Nodes: %d total | %s" % (
            len(self.nodes),
            ", ".join("%s=%d" % (k, counts[k]) for k in sorted(counts)),
        ))
        out.append("// Relationships: %d" % len(self.rels))
        out.append("//")
        out.append("// Useful checks:")
        out.append("//   MATCH (l:Lecture {id:'%s'})-[:HAS_CHAPTER]->(:Chapter)"
                   "-[:HAS_TOPIC]->(t) RETURN t.index, t.name ORDER BY t.index;"
                   % self.nodes[0][1])
        out.append("//   MATCH p=(t:Topic)-[:HAS_SUBTOPIC|HAS_CONCEPT*]->(n) RETURN p;")
        return "\n".join(out) + "\n"


def main():
    if len(sys.argv) < 2:
        sys.exit("Usage: python3 json_to_cypher.py structure.json [output.cypher]")
    with open(sys.argv[1], encoding="utf-8") as fh:
        data = json.load(fh)

    b = Builder()
    b.build(data)
    cypher = b.to_cypher()

    if len(sys.argv) >= 3:
        with open(sys.argv[2], "w", encoding="utf-8") as fh:
            fh.write(cypher)
        print("Wrote %s (%d nodes, %d relationships)."
              % (sys.argv[2], len(b.nodes), len(b.rels)))
    else:
        sys.stdout.write(cypher)


if __name__ == "__main__":
    main()
